// <auto-generated />
using System;
using ApiEonix;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiEonix.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210527150826_createtableUser")]
    partial class createtableUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("ApiEonix.Models.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff4fadb2-660a-4494-87d5-39f8a6549a08"),
                            LastName = "Lepoint",
                            Name = "Thomas"
                        },
                        new
                        {
                            Id = new Guid("850b41d5-1e98-46ea-9f64-6918b619eca9"),
                            LastName = "Leblanc",
                            Name = "Juste"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
